apiVersion: v1
kind: PersistentVolume
metadata:
  name: flask-data-pv
spec:
  capacity:
    storage: 100Mi  # Capacidad de almacenamiento
  accessModes:
    - ReadWriteOnce  # Modo de acceso (puede personalizarse según tus necesidades)
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /data/flask-data  # Ruta en el nodo donde se almacenan los datos

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flask-data-pvc
spec:
  accessModes:
    - ReadWriteOnce  # Debe coincidir con el modo de acceso del PersistentVolume
  resources:
    requests:
      storage: 100Mi  # Debe coincidir con la capacidad del PersistentVolume
